<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MathExpressions\**" />
    <Compile Remove="Serialization\BinarySerialization\NSD\**" />
    <Compile Remove="Types\Collections\Hierarchical\Trie\**" />
    <EmbeddedResource Remove="MathExpressions\**" />
    <EmbeddedResource Remove="Serialization\BinarySerialization\NSD\**" />
    <EmbeddedResource Remove="Types\Collections\Hierarchical\Trie\**" />
    <None Remove="MathExpressions\**" />
    <None Remove="Serialization\BinarySerialization\NSD\**" />
    <None Remove="Types\Collections\Hierarchical\Trie\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove=".gitattributes" />
    <None Remove=".gitignore" />
    <None Remove="LICENSE" />
    <None Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Serialization\BinarySerialization\ADF\IO\Reading\" />
    <Folder Include="Serialization\BinarySerialization\ADF\Registries\Registries\" />
    <Folder Include="Serialization\BinarySerialization\ADF\Serialization\" />
    <Folder Include="Serialization\BinarySerialization\ADF\Structure\Pages\Metadata\" />
    <Folder Include="Serialization\BinarySerialization\ADF\Structure\Pages\Page\" />
    <Folder Include="Serialization\BinarySerialization\Serializers\Object\" />
    <Folder Include="STP\Parser\Static\" />
    <Folder Include="STP\Parser\Dynamic\" />
    <Folder Include="STP\Semantic\Data\" />
    <Folder Include="STP\Source\Text\Document\" />
    <Folder Include="STP\Source\Text\Source\Base\" />
    <Folder Include="STP\Source\Text\Source\Source\" />
  </ItemGroup>

</Project>
